export const GET_REPORT_ACTION = "GET_REPORT_ACTION";
export const GET_REPORT_ACTION_DONE = "GET_REPORT_ACTION_DONE";

export const ADD_OPERATION_ACTION = "ADD_OPERATION_ACTION";
export const ADD_OPERATION_ACTION_DONE = "ADD_OPERATION_ACTION_DONE";